const translations = {
    en: {
        inferModelConfig:'Model Config',
        inferModel:'Model:',
        inferTileSize:'Tile Size:',
        inferScale:'Scale:',
        inferSkipAlpha:'SkipAlpha:',
        inferResizeTo:'Resize To:',
        inferProcessImage:'Process Image',
        inferInputImage:'Input Image:',
        inferInputFolder:'Input Folder:',
        inferSaveTo:'Save To:',
        inferProgress:'Progress:',
        inferBatchProcess:'Batch Process:',
        inferSelectButton:'Select',
        inferStartButton:'Start',
        inferAlertFinish:'Your image has been processed.',
        inferAlertError:'An error occurred while processing your image.',
        inferAlertMissingParam:'Missing required parameters (model or inputs and outputs)',
        updateNotification:"Updates and notifications are available on Github",
        inferAdvancedSettings: 'Advanced Settings',
        inferScalingMode: 'Scaling Mode:',
        inferManualScale: 'Manual Scale',
        inferTargetResolution: 'Target Resolution',
        inferTargetSize: 'Target Size:',
        settingsAlwaysShowAdvanced: 'Always Show Advanced Settings',
        settingsCustomFilename: 'Custom Filename Format:',
        settingsInsertFilestem: 'Insert {filestem}',
        settingsInsertScale: 'Insert {scale}',
        settingsInsertModelName: 'Insert {model_name}',
        settingsResetDefault: 'Default',
        settingsSameAsInput: 'Same as Input',
        settingsSaveButton: 'Save Settings',
        settingsFilenameError: 'Filename contains illegal characters: \\ / : * ? " < > |',
        // Workflow
        workflowTitle: 'Workflow',
        workflowRun: 'Run Workflow',
        workflowNodePalette: 'Nodes',
        workflowDragHint: 'Drag nodes here',
        workflowRunning: 'Workflow Running...',
        workflowFinished: 'Workflow Finished',
        workflowDeleteNode: 'Delete',
        nodeInput: 'Input',
        nodeOutput: 'Output',
        nodeInference: 'Inference',
        nodeScale: 'Resize',
        nodeConditionalJump: 'Conditional',
        nodeJump: 'Jump',
        nodeLabel: 'Label',
        nodeInputPath: 'Input Path:',
        nodeInputType: 'Input Type:',
        nodeOutputPath: 'Output Path:',
        nodeModel: 'Model:',
        nodeAlgorithm: 'Algorithm:',
        nodeTileSize: 'Tile Size:',
        nodeGPU: 'GPU:',
        nodeSkipAlpha: 'Skip Alpha:',
        nodeScaleValue: 'Value:',
        nodeConditionType: 'Condition:',
        nodeOperator: 'Operator:',
        nodeCompareValue: 'Value:',
        nodeTrueJumpTo: 'If True:',
        nodeFalseJumpTo: 'If False:',
        nodeJumpTo: 'Jump To:',
        nodeLabelName: 'Label:',
        nodeConditionWidth: 'Width',
        nodeConditionHeight: 'Height',
        nodeOperatorGt: '>',
        nodeOperatorLt: '<',
        nodeOperatorEq: '=',
        workflowSelect: 'Select Workflow',
        workflowSave: 'Save',
        workflowNew: 'New',
        workflowNamePlaceholder: 'Workflow Name',
        workflowSaveSuccess: 'Workflow saved successfully',
        workflowLoadError: 'Failed to load workflow',
        workflowError: 'An error occurred',
        workflowMissingInput: 'Missing input path',
        workflowMissingOutput: 'Missing output path',
        workflowMissingModel: 'Missing algorithm or model',
        workflowMissingValue: 'Missing value',
        workflowMissingName: 'Missing name',
    },
    zh: {
        inferModelConfig:'模型配置',
        inferModel:'模型:',
        inferTileSize:'分块大小:',
        inferScale:'放大倍率:',
        inferSkipAlpha:'跳过透明通道:',
        inferResizeTo:'缩放为:',
        inferProcessImage:'处理图片',
        inferInputImage:'待处理图片:',
        inferInputFolder:'待处理文件夹:',
        inferSaveTo:'保存位置:',
        inferProgress:'处理进度:',
        inferBatchProcess:'批量处理:',
        inferSelectButton:'选 择',
        inferStartButton:'开始处理',
        inferAlertFinish:'图片已处理完成',
        inferAlertError:'处理发生了错误',
        inferAlertMissingParam:'缺少必填参数(模型/待处理图片/保存位置)',
        updateNotification:'更新与通知可从Github获取',
        inferAdvancedSettings: '高级设置',
        inferScalingMode: '缩放模式:',
        inferManualScale: '手动缩放',
        inferTargetResolution: '目标分辨率',
        inferTargetSize: '目标尺寸:',
        settingsAlwaysShowAdvanced: '常驻显示高级设置',
        settingsCustomFilename: '自定义文件名格式:',
        settingsInsertFilestem: '插入 {filestem}',
        settingsInsertScale: '插入 {scale}',
        settingsInsertModelName: '插入 {model_name}',
        settingsResetDefault: '默认格式',
        settingsSameAsInput: '仅文件名',
        settingsSaveButton: '保存设置',
        settingsFilenameError: '文件名包含非法字符: \\ / : * ? " < > |',
        // Workflow
        workflowTitle: '工作流',
        workflowRun: '运行工作流',
        workflowNodePalette: '节点',
        workflowDragHint: '拖拽节点到此处',
        workflowRunning: '工作流运行中...',
        workflowFinished: '工作流已完成',
        workflowDeleteNode: '删除',
        nodeInput: '输入',
        nodeOutput: '输出',
        nodeInference: '推理',
        nodeScale: '调整大小',
        nodeConditionalJump: '条件跳转',
        nodeJump: '跳转',
        nodeLabel: '标签',
        nodeInputPath: '输入路径:',
        nodeInputType: '输入类型:',
        nodeOutputPath: '输出路径:',
        nodeModel: '模型:',
        nodeAlgorithm: '算法:',
        nodeTileSize: '分块大小:',
        nodeGPU: 'GPU:',
        nodeSkipAlpha: '跳过透明:',
        nodeScaleValue: '值:',
        nodeConditionType: '条件:',
        nodeOperator: '运算符:',
        nodeCompareValue: '值:',
        nodeTrueJumpTo: '成立:',
        nodeFalseJumpTo: '不成立:',
        nodeJumpTo: '跳转到:',
        nodeLabelName: '标签名:',
        nodeConditionWidth: '宽度',
        nodeConditionHeight: '高度',
        nodeOperatorGt: '>',
        nodeOperatorLt: '<',
        nodeOperatorEq: '=',
        workflowSelect: '选择工作流',
        workflowSave: '保存',
        workflowNew: '新建',
        workflowNamePlaceholder: '工作流名称',
        workflowSaveSuccess: '工作流保存成功',
        workflowLoadError: '加载工作流失败',
        workflowError: '处理发生了错误',
        workflowMissingInput: '缺少输入路径',
        workflowMissingOutput: '缺少输出路径',
        workflowMissingModel: '缺少算法或模型',
        workflowMissingValue: '缺少值',
        workflowMissingName: '缺少名称',
    },
};

export default translations;
